<?php
 
//   $conexao = ibase_connect("localhost:c:/DataBase_ICEA/Ensino/BD_Ensino.gdb","sysdba","u2u6#icea");
//   $conexao = ibase_connect("192.168.24.121:/var/lib/firebird/data/BD_PROSIMA.GDB","sysdba","u2u6#icea");
//   $conexao = ibase_connect("192.168.24.121:/var/lib/firebird/2.5/data/Ensino.gdb","sysdba","u2u6#icea");
 //  $conexao = ibase_connect("192.168.24.121:/var/lib/firebird/2.5/data/BD_Ensino.gdb","sysdba","b2e5#ensino");
$conexao = ibase_connect("192.168.24.121:/var/lib/firebird/2.5/data/BD_Ensino.gdb","sysdba","u2u6#icea");
?>
