object Frame_TrataSelCurso: TFrame_TrataSelCurso
  Left = 0
  Top = 0
  Width = 546
  Height = 116
  Ctl3D = False
  ParentCtl3D = False
  TabOrder = 0
  object JvGradient3: TJvGradient
    Left = 0
    Top = 0
    Width = 546
    Height = 116
    Align = alClient
    Style = grVertical
    StartColor = 16775660
    EndColor = 8355711
  end
  object Shape7: TShape
    Left = 4
    Top = 7
    Width = 483
    Height = 91
    Brush.Color = 16775660
    Shape = stRoundRect
  end
  object Label_Curso: TLabel
    Left = 12
    Top = 13
    Width = 109
    Height = 20
    Caption = 'C'#243'digo Curso'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label_Turma: TLabel
    Left = 10
    Top = 43
    Width = 46
    Height = 17
    Caption = 'Turma:'
    Color = 16775660
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Label_termino: TLabel
    Left = 218
    Top = 72
    Width = 58
    Height = 17
    Caption = 'T'#233'rmino:'
    Color = 16775660
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object JvShape_Base: TJvShape
    Left = 326
    Top = 10
    Width = 142
    Height = 26
    Pen.Color = 33023
  end
  object JvExpressButton_ItensBase: TJvExpressButton
    Left = 327
    Top = 11
    Width = 140
    Height = 24
    Hint = 'Inserir Itens Base na Turma selecionada'
    DragCursor = crHandPoint
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    FillColor = clLime
    Caption = 'Inserir Itens Base'
    HighlightFont.Charset = ANSI_CHARSET
    HighlightFont.Color = clBlack
    HighlightFont.Height = -13
    HighlightFont.Name = 'Arial'
    HighlightFont.Style = []
    ImageIndex = 2
    ImageSize = isSmall
    ParentImageSize = False
    LargeImages = DM.ImageList_Principal
    Spacing = 3
    SmallImages = DM.ImageList_Principal
  end
  object Label_inicio: TLabel
    Left = 11
    Top = 72
    Width = 37
    Height = 17
    Caption = 'In'#237'cio:'
    Color = 16775660
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
  end
  object Label_DescricaoCurso: TLabel
    Left = 405
    Top = 120
    Width = 130
    Height = 16
    Caption = 'Label_DescricaoCurso'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Transparent = True
    Visible = False
  end
  object ComboBox_Curso: TComboBox
    Left = 124
    Top = 12
    Width = 145
    Height = 24
    BevelInner = bvSpace
    BevelKind = bkFlat
    CharCase = ecUpperCase
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 16
    ParentFont = False
    TabOrder = 0
  end
  object ComboBox_Turma: TComboBox
    Left = 59
    Top = 40
    Width = 407
    Height = 24
    BevelInner = bvSpace
    BevelKind = bkFlat
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 16
    ParentFont = False
    TabOrder = 1
  end
  object DBEdit_Inicio: TDBEdit
    Left = 54
    Top = 69
    Width = 102
    Height = 24
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    DataField = 'DATAINICIO'
    DataSource = DM.DSQ_MontaTurma
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 2
  end
  object DBEdit_Termino: TDBEdit
    Left = 281
    Top = 69
    Width = 102
    Height = 24
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    DataField = 'DATATERMINO'
    DataSource = DM.DSQ_MontaTurma
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 3
  end
end
