object Frame_SelCurso: TFrame_SelCurso
  Left = 0
  Top = 0
  Width = 443
  Height = 113
  Align = alTop
  AutoSize = True
  Ctl3D = False
  ParentCtl3D = False
  TabOrder = 0
  object Panel_SelCurso: TPanel
    Left = 0
    Top = 0
    Width = 745
    Height = 113
    BevelOuter = bvNone
    BorderStyle = bsSingle
    TabOrder = 0
    object JvGradient3: TJvGradient
      Left = 0
      Top = 0
      Width = 743
      Height = 111
      Align = alClient
      Style = grVertical
      StartColor = 4227200
      EndColor = 16777190
      Steps = 60
    end
    object Label_CodCurso: TLabel
      Left = 11
      Top = 5
      Width = 94
      Height = 17
      Caption = 'C'#243'digo Curso:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object Label_Turma: TLabel
      Left = 8
      Top = 33
      Width = 40
      Height = 16
      Caption = 'Turma:'
      Color = 16577515
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
    end
    object Label_Termino: TLabel
      Left = 168
      Top = 59
      Width = 50
      Height = 16
      Caption = 'T'#233'rmino:'
      Color = 16577515
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
    end
    object Label_Inicio: TLabel
      Left = 12
      Top = 59
      Width = 34
      Height = 16
      Caption = 'Inicio:'
      Color = 16577515
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
    end
    object Label_TerminoDist: TLabel
      Left = 8
      Top = 84
      Width = 77
      Height = 16
      Caption = 'Coordenador:'
      Color = 16577515
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
    end
    object ComboBox_Curso: TComboBox
      Left = 110
      Top = 1
      Width = 145
      Height = 24
      BevelInner = bvSpace
      BevelKind = bkFlat
      CharCase = ecUpperCase
      Color = 11192063
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 16
      ParentFont = False
      TabOrder = 0
      OnChange = ComboBox_CursoChange
    end
    object ComboBox_Turma: TComboBox
      Left = 51
      Top = 29
      Width = 686
      Height = 24
      BevelInner = bvSpace
      BevelKind = bkFlat
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 16
      ParentFont = False
      TabOrder = 1
      OnChange = ComboBox_TurmaChange
      OnKeyPress = ComboBox_TurmaKeyPress
    end
    object DBEdit_Inicio: TDBEdit
      Left = 52
      Top = 55
      Width = 98
      Height = 23
      BevelInner = bvSpace
      BevelKind = bkFlat
      BorderStyle = bsNone
      DataField = 'DATAINICIO'
      DataSource = DM.DSQ_MontaTurma
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
    end
    object DBEdit_Termino: TDBEdit
      Left = 219
      Top = 55
      Width = 98
      Height = 23
      BevelInner = bvSpace
      BevelKind = bkFlat
      BorderStyle = bsNone
      DataField = 'DATATERMINO'
      DataSource = DM.DSQ_MontaTurma
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
    end
    object DBEdit_Coordenador: TDBEdit
      Left = 91
      Top = 80
      Width = 630
      Height = 23
      BevelInner = bvSpace
      BevelKind = bkFlat
      BorderStyle = bsNone
      DataField = 'COORDENADOR'
      DataSource = DM.DSQ_MontaTurma
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
    end
  end
end
