<?php

   // ------ configurações do gráfico ----------
   $largura = 380; //600;
   $altura = 250;  //400;

   // ------ configurações do círculo ----------
   $centrox = 120;  //200;
   $centroy = 120;  //200;
   $diametro = 140; //280;
   $angulo = 0;

   // ------ configurações da legenda ----------
   $exibir_legenda = "sim";
   $fonte = 3;
   $largura_fonte = 8; // largura em pixels (2=6,3=8,4=10)
   $altura_fonte = 10; // altura em pixels (2=8,3=10,4=12)
   $espaco_entre_linhas = 10;
   $margem_vertical = 5;

   // canto superior direito da legenda
   $lx = 350; // 540;
   $ly = 30;

?>
